# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 633e289df65f1ac937e45324c1a0210111af1dbaf1b49d4f195233efed2bd558958899e4f9601e7e16c181cb932b4980f1593e00eede5fc8cde1e83ff3fa3f50

test:
  secret_key_base: dd58d652955cf85300491342fed5f2a09afce106b339619c366d082cb179363602ee4ec5a3d7c818782ed7cf11d257c76ad54ed92a475ee009b65e2c5376ca53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
